[package]
name = "provwasm-test-tube"
version = "0.1.0"
repository = "https://github.com/provenance-io/provwasm-test-tube"
edition = "2021"
license = "Apache-2.0"
description = "library for building smart contract integration testing environments for Provenance Blockchain in Rust"
keywords = ["provenance", "blockchain", "smart-contracts", "defi", "finance"]
categories = ["api-bindings", "cryptography::cryptocurrencies", "wasm"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

exclude = ["provenance", "test_artifacts"]

[dependencies]
base64 = "0.21.5"
cosmrs = { version = "0.14.0", features = ["cosmwasm"] }
cosmwasm-std = "1.2.5"
provwasm-std = { version = "2.2.0" }
prost = { version = "0.11.9", default-features = false, features = ["prost-derive"] }
serde = "1.0.144"
serde_json = "1.0.85"
test-tube-prov = { version = "0.1.0", path = "../test-tube" }
thiserror = "1.0.34"

[build-dependencies]
bindgen = "0.69.1"

[dev-dependencies]
cw1-whitelist = "1.1.1"
rayon = "1.5.3"
