[package]
description = "Provwasm integration testing for Provenance"
edition = "2021"
license = "MIT OR Apache-2.0"
name = "provwasm-test-tube"
repository = "https://github.com/provenance-io/test-tube"
version = "0.1.0"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

exclude = ["provenance", "test_artifacts"]

[dependencies]
base64 = "0.21.5"
cosmrs = {version = "0.14.0", features = ["cosmwasm"]}
cosmwasm-std = "1.2.5"
provwasm-std = {version = "2.1.0", path = "../../../provwasm/packages/provwasm-std"}
prost = {version = "0.11.9", default-features = false, features = ["prost-derive"]}
serde = "1.0.144"
serde_json = "1.0.85"
test-tube = {version = "0.1.0", path = "../test-tube"}
thiserror = "1.0.34"

[build-dependencies]
bindgen = "0.68.1"

[dev-dependencies]
cw1-whitelist = "1.1.1"
rayon = "1.5.3"
