[package]
description = "library for building integration testing environments for cosmos-sdk chains in Rust"
edition = "2021"
license = "MIT OR Apache-2.0"
name = "test-tube"
repository = "https://github.com/provenance-io/test-tube"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.13.0"
cosmrs = {version = "0.9.0", features = ["cosmwasm", "rpc"]}
cosmwasm-std = {version = "1.4.0", features = ["stargate"]}
provwasm-std = {version = "2.1.0", optional = true, path = "../../../provwasm/packages/provwasm-std"}
prost = "0.11.9"
serde = "1.0.144"
serde_json = "1.0.85"
thiserror = "1.0.34"

[dev-dependencies]
cw1-whitelist = "0.15.0"
rayon = "1.5.3"

[features]
default = []

all-modules = ["bank", "wasm"]

bank = ["provwasm-std"]
wasm = ["provwasm-std"]
