[package]
name = "test-tube-prov"
version = "0.1.0-rc1"
repository = "https://github.com/provenance-io/provwasm-test-tube"
edition = "2021"
license = "Apache-2.0"
authors = ["Ken Talley <4344285+kwtalley@users.noreply.github.com"]
description = "library for building smart contract integration testing environments for Provenance Blockchain in Rust"
keywords = ["provenance", "blockchain", "smart-contracts", "defi", "finance"]
categories = ["api-bindings", "cryptography::cryptocurrencies", "wasm"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.22.0"
cosmrs = { version = "0.14.0", features = ["cosmwasm", "rpc"] }
cosmwasm-std = { version = "1.5", features = ["stargate"] }
provwasm-std = { version = "2.2.0" }
prost = "0.11.9"
serde = "1.0.197"
serde_json = "1.0.115"
tendermint-proto = "0.32.0"
thiserror = "1.0.58"

[dev-dependencies]
cw1-whitelist = "0.15.0"
rayon = "1.5.3"
